jobs:
  include:

  - stage: test
    language: java
    jdk: openjdk11
    cache:
      directories:
        - $HOME/.m2

    before_install: cd eventcenter-backend
    install: true

    script: mvn -B test  # mvn clean install is működne

  - stage: test
    language: node_js
    node_js: node
    addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
    before_install: cd eventcenter-client
    script: npm run test:ci

  - stage: deploy1
    language: java
    jdk: openjdk11
    cache:
      directories:
        - $HOME/.m2
    before_install: cd eventcenter-backend
    install: true
    script: skip
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "uMBg/IzQ0y6TZ840pkkVmwcLlrl/r6S8CAgPtRF66cTbPSS8one+hjXvVNg5xgalhzg8HCDv+lyOqlcoYmrGmQKMqtqbI2dRypp5uDSBPRgYIdBG8Qa2/gNTcK87/SYWqA3fsveybSh+Iqzld2wpmIGbxyQY6PPXJiZyS98bIsIBA6E/TLnssKIQRDxvedZk6Omu1CV7ay3PdBsibdSkWhP6mSF3CtkLaVW9KLheMOIKp+GW+s1H55dh66vg/ESGA7EmtX/tDqvXaD0tWpwR1yslvRiZaAUq/fkpaaFrW8YdKW1EVFBV/1Uxt6mAdsIq4BUXguhuV7syHqUFV/CD6Jgc+pnvrSiAfPmkwjWRIJH1TJ0g3io99AtBEp/mNleD4lBTqMaN9UQHpbGwLPQ3h94corJ1bpYFwpFp4R5KIgcZ3NY3KTVna7uRGXGI/x63RvqSgozxyR2sjuxSWWtCVJivBQ4Dbhg2Cmc9C/g15V9txrULu8g9p4v5WAMf8NejUwx+HgGXaPB0UnklIKy/rot2+KFT7Kjbkq+6upp3zz2xIVIxbFTij7quNy6utQQFDmdkF6YWFpjQNMjLCtz5DsHZApzMdFUU9gPx5QHu72Cdbit+c0VQThqyxoGBjt/7VcCT2B9R6og40x5Sxgg1rZIMq41zpKjhaJWmbiazuis="
      app: eventcenter-backend
      on: main

  - stage: deploy2
    language: node_js
    node_js: node
    before_install: cd eventcenter-client
    script: skip
    after_success: npm run build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: 'uMBg/IzQ0y6TZ840pkkVmwcLlrl/r6S8CAgPtRF66cTbPSS8one+hjXvVNg5xgalhzg8HCDv+lyOqlcoYmrGmQKMqtqbI2dRypp5uDSBPRgYIdBG8Qa2/gNTcK87/SYWqA3fsveybSh+Iqzld2wpmIGbxyQY6PPXJiZyS98bIsIBA6E/TLnssKIQRDxvedZk6Omu1CV7ay3PdBsibdSkWhP6mSF3CtkLaVW9KLheMOIKp+GW+s1H55dh66vg/ESGA7EmtX/tDqvXaD0tWpwR1yslvRiZaAUq/fkpaaFrW8YdKW1EVFBV/1Uxt6mAdsIq4BUXguhuV7syHqUFV/CD6Jgc+pnvrSiAfPmkwjWRIJH1TJ0g3io99AtBEp/mNleD4lBTqMaN9UQHpbGwLPQ3h94corJ1bpYFwpFp4R5KIgcZ3NY3KTVna7uRGXGI/x63RvqSgozxyR2sjuxSWWtCVJivBQ4Dbhg2Cmc9C/g15V9txrULu8g9p4v5WAMf8NejUwx+HgGXaPB0UnklIKy/rot2+KFT7Kjbkq+6upp3zz2xIVIxbFTij7quNy6utQQFDmdkF6YWFpjQNMjLCtz5DsHZApzMdFUU9gPx5QHu72Cdbit+c0VQThqyxoGBjt/7VcCT2B9R6og40x5Sxgg1rZIMq41zpKjhaJWmbiazuis='
      app: eventcenter-client
      on: main